---
title: "Cancer Incidences Borders"
author: "Stuart McColl"
date: "14/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**bold**  
*italic*  
<http://rmarkdown.rstudio.com>  
[link](http://rmarkdown.rstudio.com)  

* unordered list
    + sub-item 1
    + sub-item 2
    
1. ordered list
  i) sub-item
2. item 2

*** 
    

## Analysis

```{r, warning = FALSE, message = FALSE, echo = FALSE}

library(tidyverse)

health_board_level_clean <-
  read_csv("/Users/Natifu/codeclan_homework_StuartM/week_09/tech_question_cancer_rates/clean_data/health_board_level_clean")

scotland_level_clean <-
  read_csv("/Users/Natifu/codeclan_homework_StuartM/week_09/tech_question_cancer_rates/clean_data/scotland_level_clean")


```


### Show Number of Incidences Across Scotland Over Time

```{r,echo = FALSE}

scotland_level_clean %>% 
  filter(cancer_type == "All") %>% 
  filter(age_group == "All") %>% 
  ggplot(aes(x = year, y = number_of_incidences, colour = sex)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(breaks = c(1994, 1995, 1996, 1997, 1998, 1999,
                                2000, 2001, 2002, 2003, 2004, 2005, 2006,
                                2007, 2008, 2009, 2010, 2011, 2012, 2013,
                                2014, 2015, 2016, 2017, 2018)) +
  labs(x = "Year", y = "Number of Incidences", title = "Number of Cancer Incideneces Across Scotland") +
  theme_light() +
  theme(axis.text.x = element_text(angle = 90))
  


```

### Show Number of Incidences in Each Health Board Over Time
#### From 1994 to 2018:

```{r, echo=FALSE, warning=FALSE, message=FALSE}

health_board_level_clean %>% 
  group_by(health_board_name) %>% 
  filter(cancer_type == "All") %>% 
  summarise(total_number_of_incidences = sum(number_of_incidences)) %>% 
  arrange(desc(total_number_of_incidences))

```



### Show Number of Incidences in Borders Over Time for All Cancer - graph
### Show Number of Incidences in Borders Over Time for Individual Cancers - table







